import Footer from '@/components/footer/footer';
import NavBar from '@/components/nav-bar/nav-bar';
import { NAV_BAR_ITEMS } from '@/constants';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Page',
  description: 'Generated by create next app',
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className='flex h-ful w-full flex-col gap-10'>
      <NavBar />
      {children}
      <Footer links={NAV_BAR_ITEMS} />
    </div>
  );
}
